dist: xenial

language: java

jdk: openjdk11

node_js:
  - 10

addons:
  sonarcloud:
    organization: "facebook-final-project"
    token: ${SONAR_CLOUD_TOKEN}
    
cache:
  directories:
  - $HOME/.m2
  - ./frontend/mobile/node_modules/

before_install:
  - nvm install 10

before_script:
  - npm install --prefix frontend/mobile/

script:
  - mvn clean test jacoco:report coveralls:report
  - sonar-scanner

