dist: trusty

language: java

jdk:
  - oraclejdk8

node_js:
  - 10

cache:
  directories:
  - $HOME/.m2
  - ./frontend/mobile/node_modules/

before_install:
  - nvm install 10

before_script:
  - npm install --prefix frontend/mobile/

script:
  - mvn clean test
  - npm run build --prefix frontend/mobile/