spring:
  profiles:
    active: dev

etsyProperties:
  credentials:
    key: ${ETSY_KEY:KEY_DUMMY}
    secret: ${ETSY_SECRET:SECRET_DUMMY}
    shopId: ${ETSY_SHOP_ID:SHOP_ID_DUMMY}
    token: ${ETSY_TOKEN:TOKEN_DUMMY}
    tokenSecret: ${ETSY_TOKEN_SECRET:TOKEN_SECRET_DUMMY}